# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurrent_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('concurrent_type', models.CharField(max_length=255)),
                ('status', models.CharField(default='P', max_length=255)),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('enddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('param_value', models.CharField(default=None, max_length=255)),
                ('increment_value', models.IntegerField(default=1)),
                ('task_id', models.CharField(default=None, max_length=255)),
                ('created_by', models.IntegerField(default=4)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('last_update_by', models.IntegerField(default=4)),
                ('last_update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update Date')),
            ],
            options={
                'db_table': 'Concurrent_list',
            },
        )
    ]
