# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concurrent_list',
            new_name='ConcurrentList',
        ),
    ]
