# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0002_auto_20171218_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrentlist',
            name='task_id',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
