# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0004_concurrentlist2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='last_update_date',
        ),
    ]
