# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0005_remove_concurrentlist2_last_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='last_update_by',
        ),
    ]
