# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0006_remove_concurrentlist2_last_update_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='increment_value',
        ),
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='param_value',
        ),
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='concurrentlist2',
            name='url',
        ),
    ]
