# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0007_auto_20171219_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConcurrentList2',
        ),
    ]
