# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0008_delete_concurrentlist2'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='masterconcurrentdetail',
    #         name='concurrent_id',
    #     ),
    #     migrations.DeleteModel(
    #         name='MasterConcurrent',
    #     ),
    #     migrations.DeleteModel(
    #         name='MasterConcurrentDetail',
    #     ),
    # ]
