# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0009_auto_20171221_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurrentlist',
            name='concurrent_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='concurrent_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='created_by',
            field=models.IntegerField(blank=True, db_index=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='enddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='increment_value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='last_update_by',
            field=models.IntegerField(blank=True, db_index=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='last_update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='param_value',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='startdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='status',
            field=models.CharField(blank=True, default='P', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='task_id',
            field=models.CharField(db_index=True, default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
