# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0011_concurrentlist_actual_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurrentlist',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concurrentlist',
            name='date_submit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
