# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0012_auto_20180108_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrentlist',
            name='increment_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='param_value',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='task_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
