# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0013_auto_20180108_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurrentlist',
            name='concurrent_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
