# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0002_auto_20180111_0951'),
        ('concurrentManager', '0014_concurrentlist_concurrent_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurrentlist',
            name='concurrent_id',
            field=models.ForeignKey(db_column='MasterConcurrent_id', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='concurrent_id', to='masterConcurrent.MasterConcurrent'),
        ),
    ]
