# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0015_concurrentlist_concurrent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrentlist',
            name='concurrent_id',
            field=models.ForeignKey(db_column='MasterConcurrent_list_id', default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='concurrent_id', to='masterConcurrent.MasterConcurrent'),
        ),
    ]
