# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0017_auto_20180111_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurrentlist',
            name='phase',
            field=models.CharField(blank=True, default='P', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
