# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0020_merge_20180129_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurrentlist',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='concurrentlist',
            name='date_submit',
        ),
        migrations.RemoveField(
            model_name='concurrentlist',
            name='last_update_by',
        ),
        migrations.AddField(
            model_name='concurrentlist',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concurrentlist',
            name='last_updated_by',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concurrentlist',
            name='login_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='actual_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='actual_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='concurrent_id',
            field=models.ForeignKey(db_column='concurrent_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='MasterConcurrent_list_id', to='masterConcurrent.MasterConcurrent'),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='concurrent_name',
            field=models.CharField(db_index=True, default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='concurrent_type',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='created_by',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='param_value',
            field=models.CharField(db_index=True, default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='phase',
            field=models.CharField(default='P', max_length=255),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='status',
            field=models.CharField(default='P', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='url',
            field=models.CharField(db_index=True, default='test', max_length=255),
            preserve_default=False,
        ),
    ]
