# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0021_auto_20180130_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrentlist',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
