# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0022_auto_20180130_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrentlist',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
