# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0023_auto_20180130_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concurrentlist',
            old_name='concurrent_type',
            new_name='run_type',
        ),
    ]
