# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0026_auto_20180131_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurrentlist',
            name='interval_run_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
