# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0027_concurrentlist_interval_run_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurrentlist',
            name='concurrent_name',
        ),
        migrations.RemoveField(
            model_name='concurrentlist',
            name='url',
        ),
    ]
