# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0028_auto_20180209_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrentlist',
            name='phase',
            field=models.CharField(default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='concurrentlist',
            name='run_type',
            field=models.ForeignKey(blank=True, db_column='run_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_run_type', to='lookups.TsLookupCodes'),
        ),
    ]
