# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurrentManager', '0029_auto_20180213_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concurrentlist',
            old_name='concurrent_uuid',
            new_name='concurrent_req_uuid',
        ),
        migrations.RenameField(
            model_name='concurrentlist',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='concurrentlist',
            old_name='increment_value',
            new_name='interval_run',
        ),
        migrations.RenameField(
            model_name='concurrentlist',
            old_name='startdate',
            new_name='start_date',
        ),
        migrations.AlterModelTable(
            name='concurrentlist',
            table='ts_concurrent_request',
        ),
    ]
