# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterConcurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('concurrent_name', models.CharField(default='Test', max_length=255)),
                ('concurrent_type', models.CharField(max_length=255)),
                ('created_by', models.IntegerField(default=4)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('last_update_by', models.IntegerField(default=4)),
                ('last_update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update Date')),
            ],
            options={
                'db_table': 'MasterConcurrent_list',
            },
        ),
        migrations.CreateModel(
            name='MasterConcurrentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=255)),
                ('seq', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(default=4)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('last_update_by', models.IntegerField(default=4)),
                ('last_update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update Date')),
                ('concurrent_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masterConcurrent.MasterConcurrent')),
            ],
            options={
                'db_table': 'MasterConcurrentDetail_list',
            },
        ),
    ]
