# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterconcurrent',
            name='master_conc_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='detail_conc_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
