# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0002_auto_20180111_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterconcurrent',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterconcurrent',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='enabled_flag',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='max_character',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterconcurrent',
            name='concurrent_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='masterconcurrentdetail',
            name='seq',
            field=models.IntegerField(),
        ),
    ]
