# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0003_auto_20180112_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterconcurrentdetail',
            name='concurrent_id',
            field=models.ForeignKey(db_column='concurrent_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_detail', to='masterConcurrent.MasterConcurrent'),
        ),
    ]
