# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0004_auto_20180122_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
