# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0006_auto_20180123_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterconcurrent',
            name='concurrent_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='masterconcurrentdetail',
            name='type',
            field=models.IntegerField(blank=True),
        ),
    ]
