# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0007_auto_20180123_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='type_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
