# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0005_auto_20171208_1500'),
        ('masterConcurrent', '0008_masterconcurrentdetail_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='lookup_id',
            field=models.ForeignKey(db_column='lookup_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_conc', to='lookups.TsLookupCodes'),
        ),
    ]
