# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0010_auto_20180123_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterconcurrent',
            name='lookup_id',
            field=models.ForeignKey(db_column='lookup_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_master_conc', to='lookups.TsLookups'),
        ),
        migrations.AlterField(
            model_name='masterconcurrentdetail',
            name='lookup_id',
            field=models.ForeignKey(db_column='lookup_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_detail_conc', to='lookups.TsLookups'),
        ),
    ]
