# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0005_auto_20171208_1500'),
        ('masterConcurrent', '0011_auto_20180123_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterconcurrent',
            name='lookup_id',
        ),
        migrations.RemoveField(
            model_name='masterconcurrentdetail',
            name='lookup_id',
        ),
        migrations.AddField(
            model_name='masterconcurrent',
            name='lookup_code_id',
            field=models.ForeignKey(db_column='lookup_code_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_master_conc', to='lookups.TsLookupCodes'),
        ),
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='lookup_code_id',
            field=models.ForeignKey(db_column='lookup_code_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_detail_conc', to='lookups.TsLookupCodes'),
        ),
    ]
