# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0014_auto_20180124_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterconcurrentdetail',
            name='type',
        ),
    ]
