# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0016_auto_20180130_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterconcurrentdetail',
            options={'ordering': ['id']},
        ),
    ]
