# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0017_auto_20180130_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='default_value',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='display_flag',
            field=models.CharField(default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterconcurrentdetail',
            name='required_flag',
            field=models.CharField(default='y', max_length=1),
            preserve_default=False,
        ),
    ]
