# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0019_auto_20180205_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterconcurrentdetail',
            options={'ordering': ['concurrent_id', 'seq']},
        ),
    ]
