# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0021_masterconcurrentdetail_concurrent_lookup_detail_value_set_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterconcurrentdetail',
            name='concurrent_lookup_detail_value_set_id',
            field=models.ForeignKey(blank=True, db_column='concurrent_lookup_detail_value_set_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookuptype_det_conc', to='lookups.TsLookupCodes'),
        ),
    ]
