# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0022_auto_20180207_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterconcurrent',
            old_name='master_conc_uuid',
            new_name='concurrent_uuid',
        ),
        migrations.RenameField(
            model_name='masterconcurrentdetail',
            old_name='concurrent_lookup_detail_type_id',
            new_name='concurrent_lookup_param_type_id',
        ),
        migrations.RenameField(
            model_name='masterconcurrentdetail',
            old_name='concurrent_lookup_detail_value_set_id',
            new_name='concurrent_lookup_param_value_set_id',
        ),
        migrations.RenameField(
            model_name='masterconcurrentdetail',
            old_name='detail_conc_uuid',
            new_name='concurrent_param_uuid',
        ),
        migrations.RemoveField(
            model_name='masterconcurrentdetail',
            name='type_description',
        ),
        migrations.AlterModelTable(
            name='masterconcurrent',
            table='ts_concurrent',
        ),
        migrations.AlterModelTable(
            name='masterconcurrentdetail',
            table='ts_concurrent_param',
        ),
    ]
