# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterConcurrent', '0023_auto_20180214_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterconcurrentdetail',
            name='concurrent_lookup_param_type_id',
            field=models.ForeignKey(db_column='concurrent_lookup_param_type_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_detail_conc', to='lookups.TsLookupCodes'),
        ),
    ]
